### PR TITLE
SnakeGame

### PR DESCRIPTION
**Pull request by zenit-abh**
Please have a look at my code of snake game

### CODE REVIEW

**Comment by zenit-abh** [comment]
@ankitdobhal Sir please have a look. Merge Request number #151

**Comment by zenit-abh** [comment]
@ankitdobhal Sir please have a look.

**Comment by zenit-abh** [comment]
@SKAUL05 Sir its been quite a long since I opened this pull request please do have a look.

**Review by SKAUL05 — APPROVED** [review]

**Comment by zenit-abh** [comment]
Thank you @SKAUL05 sir

**Pull request merged**
