### PR TITLE
Questions from project euler

### PR DESCRIPTION
**Pull request by Namyalg**
This script can be used to obtain all the questions of Project Euler.

Issue related to #92

### CODE REVIEW

**Comment by Neilblaze** [comment]
Beautiful work @Namyalg ! :smiley: 
But tell me one thing, why have you kept the pr files into `System-Automation-Scripts` directory?
If this is a web-scraping script, this should have been into the web-scraping folder right?

Make the necessary changes & let me know ok?

**Comment by Namyalg** [comment]
I am extremely sorry. I pushed it into the wrong folder. Will change it
right away.

**Review by Neilblaze — COMMENTED** [review]
Nice work! :smiley:

**Review by Neilblaze — APPROVED** [review]
LGTM :+1:

**Pull request merged**
