### PR TITLE
Password Checker

### PR DESCRIPTION
**Pull request by Gaurav451**
Made this password checker to check  how many times password has been used,either on anonymous websites,or the websites you generally use.

### CODE REVIEW

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
Include script inside a folder. 
There is no extension to the file.

**Comment by Gaurav451** [comment]
So,do i need to close request or i can do that in this request only?

**Comment by SKAUL05** [comment]
> So,do i need to close request or i can do that in this request only?

in this request only

**Comment by Gaurav451** [comment]
do i have to make a new folder on desktop and put this python file in it and then upload it?

**Comment by Gaurav451** [comment]
I am not able to upload the zip file of the project.

**Pull request closed without merging**
