### PR TITLE
Added Links Extractor Script

### PR DESCRIPTION
**Pull request by harshareddy794**
This is a links extractor script using BS4. This actually scan through a web page and extract all the available links on that page and 
save all available links data to an XLS fils #92 
Screenshot (59)

### CODE REVIEW

**Comment by Neilblaze** [comment]
Thank you for your contribution @harshareddy794 !

Before I approve changes to the PR, I will request you the following changes mentioned below.

- Add README (guide) along with this inside the folder same as your `<filename>`
- Shift most of the comments as instructions in the README file.
- Maintain proper [Contribution protocols](https://github.com/ankitdobhal/Awesome-Python-Scripts/blob/master/Contribution.md) (ignore if you're already following it!) & [good practices](https://gist.github.com/sloria/7001839)!
- Recheck if there are any intendation errors in the script.

Rest LGTM :+1:

**Review by Neilblaze — CHANGES_REQUESTED** [review]
Create a README file withing the same directory of the `<filename>` branch & paste most of the comments to that as instructions. Or better create the appropriate instructions within the README file!

**Comment by harshareddy794** [comment]
Sure will do that @Neilblaze

**Comment by harshareddy794** [comment]
@Neilblaze Can you please check

**Comment by Neilblaze** [comment]
Nice job @harshareddy794! :tada: 
LGTM :+1:

**Review by Neilblaze — APPROVED** [review]

**Comment by harshareddy794** [comment]
@ankitdobhal  My PR has not yet merged can you check

**Comment by Neilblaze** [comment]
There are lots of other PR's and issues to be resolved by the mentors and PA's. No worries, @ankitdobhal will merge this when he'll be available.

**Pull request merged**
