### PR TITLE
Added word_detector to System Automation Scripts

### PR DESCRIPTION
**Pull request by AdityaJ7**
This script will enable us to flag the files which contain the target word provided by the user and will move these files into a separate folder for easy access.

This pull request is related to issue #94

### CODE REVIEW

**Comment by Neilblaze** [comment]
Thank you for your contribution @AdityaJ7 !

Before I approve changes to the PR, I will request you the following changes mentioned below.

~~- After forking this repo, **checkout** a **new branch** with your `<filename>`!~~
- Add README (guide) (in brief) along with this inside the folder same as your `<filename>`
- Maintain proper [Contribution protocols](https://github.com/ankitdobhal/Awesome-Python-Scripts/blob/master/Contribution.md) (ignore if you're already following it!) & [good practices](https://gist.github.com/sloria/7001839)!

Rest LGTM :+1: 
> nice work for maintaining nice & clean code :100:

**Comment by AdityaJ7** [comment]
> Thank you for your contribution @AdityaJ7 !
> 
> Before I approve changes to the PR, I will request you the following changes mentioned below.
> 
> ~- After forking this repo, **checkout** a **new branch** with your `<filename>`!~
> 
> * Add README (guide) (in brief) along with this inside the folder same as your `<filename>`
> * Maintain proper [Contribution protocols](https://github.com/ankitdobhal/Awesome-Python-Scripts/blob/master/Contribution.md) (ignore if you're already following it!) & [good practices](https://gist.github.com/sloria/7001839)!
> 
> Rest LGTM 👍
> 
> > nice work for maintaining nice & clean code 💯

Readme file added successfully .

**Review by Neilblaze — APPROVED** [review]
Awesome work @AdityaJ7 ! :tada:

**Comment by AdityaJ7** [comment]
> Awesome work @AdityaJ7 ! 🎉

Thanks

**Pull request merged**
