### PR TITLE
 Password checker

### PR DESCRIPTION
**Pull request by Gaurav451**
A password checker to check how many times password has been used,either on anonymous or your own used websites.

### CODE REVIEW

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
@Gaurav451 File doesn't have a extension 
Pls check it

**Comment by Gaurav451** [comment]
@SKAUL05,i have made the changes,please check it.

**Review by SKAUL05 — COMMENTED** [review]
Change file name to password_checker.py

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
You are removing pre existed stuff of README

**Comment by Gaurav451** [comment]
@SKAUL05,I didnt get it

**Comment by SKAUL05** [comment]
> @SKAUL05,I didnt get it

Check README file inside Basic Scripts folder.
You need to append ur changes in it.
But the changes u r pushing is removing the existing items.

**Comment by Gaurav451** [comment]
@SKAUL05,i have made changes,hope they are right

**Comment by SKAUL05** [comment]
> @SKAUL05,i have made changes,hope they are right

Remove Password checker info from README
As this readme is for broader perspective.
You can include the documentation in ur code itself.

Everything else LGTM:)

**Comment by Gaurav451** [comment]
@SKAUL05,please review changes.

**Review by SKAUL05 — APPROVED** [review]
Good to go
@ankitdobhal Review and merge

**Pull request merged**
