### PR TITLE
Scrap IMDB top movies

### LINKED ISSUE #195: Scrap Top Movies from IMDB
Scrap top **`250`** movies from **`IMDB`** and generate a **`CSV`** file for it

- Use [IMDB URL](https://www.imdb.com/chart/top/?ref_=nv_mv_250) for scraping

### PR DESCRIPTION
**Pull request by rutujadhanawade**
Fixes #195 
- This Python script will Scrap the details of top 250 movies from IMDB and generate a CSV file for it.
- I have used BeautifulSoup4 and pandas .

### CODE REVIEW

**Comment by rutujadhanawade** [comment]
@SKAUL05 please review this.

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
Include a results folder and add the output csv in it

**Comment by rutujadhanawade** [comment]
@SKAUL05  I have added output folder.

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
Round Up The Rating and include S.No header

**Comment by rutujadhanawade** [comment]
Okay and anything else?

**Comment by SKAUL05** [comment]
> Okay and anything else?

Nope everything else LGTM:)

**Comment by rutujadhanawade** [comment]
@SKAUL05 please Review this.

**Review by SKAUL05 — APPROVED** [review]
Good to go
@ankitdobhal Review and Merge

**Pull request merged**
