### PR TITLE
Python script to get your current location

### PR DESCRIPTION
**Pull request by abhishek-mishra17**
Added a python scrip to get current location

### CODE REVIEW

**Comment by abhishek-mishra17** [comment]
@ankitdobhal  I have added the output in the readme file.

**Comment by Neilblaze** [comment]
Amazing work @abhishek-pes ! :tada: 

Before I approve changes to the PR, I will request you the following changes mentioned below.

- Create a separate branch before pushing the files into it. 
- Exclude the `chromedriver.exe` autogenerated file from the PR file.
- Maintain proper [Contribution protocols](https://github.com/ankitdobhal/Awesome-Python-Scripts/blob/master/Contribution.md) (ignore if you're already following it!) & [good practices](https://gist.github.com/sloria/7001839)!

Rest LGTM :+1: 
> + nice & clean code :smile:

**Review by Neilblaze — CHANGES_REQUESTED** [review]
Delete the .exe file & rest LGTM :+1:

**Comment by abhishek-mishra17** [comment]
@Neilblaze  thanks a lot for the suggestions, also I have  deleted the chromedriver.exe

**Comment by Neilblaze** [comment]
> Amazing work @abhishek-pes ! 
> 
> Before I approve changes to the PR, I will request you the following changes mentioned below.
> 
> * Create a separate branch before pushing the files into it.
> * Exclude the `chromedriver.exe` autogenerated file from the PR file.
> * Maintain proper [Contribution protocols](https://github.com/ankitdobhal/Awesome-Python-Scripts/blob/master/Contribution.md) (ignore if you're already following it!) & [good practices](https://gist.github.com/sloria/7001839)!
> 
> Rest LGTM 
> 
> > * nice & clean code smile

@abhishek-pes please shift the pr folder to seperate branch as I mentioned earlier.

**Comment by abhishek-mishra17** [comment]
> > Amazing work @abhishek-pes !
> > Before I approve changes to the PR, I will request you the following changes mentioned below.
> > 
> > * Create a separate branch before pushing the files into it.
> > * Exclude the `chromedriver.exe` autogenerated file from the PR file.
> > * Maintain proper [Contribution protocols](https://github.com/ankitdobhal/Awesome-Python-Scripts/blob/master/Contribution.md) (ignore if you're already following it!) & [good practices](https://gist.github.com/sloria/7001839)!
> > 
> > Rest LGTM
> > > * nice & clean code smile
> 
> @abhishek-pes please shift the pr folder to seperate branch as I mentioned earlier.

@Neilblaze sorry I missed it, so is this correct now?

**Comment by Neilblaze** [comment]
LGTM! :+1:

**Comment by Neilblaze** [comment]
@abhishek-pes why didn't you perform the upstream of base branch before changing the base branch. As I can see the pr file still exists in the base branch. Fix this buddy!

**Comment by abhishek-mishra17** [comment]
sorry iam still a beginner, so how do I fix this?

**Comment by abhishek-mishra17** [comment]
@Neilblaze  since iam still a beginner can you please help me in fixing this.

**Comment by Neilblaze** [comment]
Since you're not much familiar with git-cli, you do one thing save the pr file on your local & start anew. If get stuck then feel free to ping me on slack!

**Pull request closed without merging**
