### PR TITLE
Instagram scrapper

### LINKED ISSUE #92: Add Some Cool Web-Scraping Scripts
# This is a easy and medium level  Issue.
- **Web scraping is data scraping technique used for extracting data from websites.**
- **Try to add some basic and advance web scraping scripts in Web-Scraping folder.**

# Comment on the issue and start contributing

### PR DESCRIPTION
**Pull request by rutujadhanawade**
- This script is written in Python. It takes the username as input and return the number of posts, followers and following. 
- I have used Beautifulsoup and requests.
- #92

### CODE REVIEW

**Comment by rutujadhanawade** [comment]
@ankitdobhal @Neilblaze @SKAUL05 will you please review this, As a part of CH20.

**Comment by Neilblaze** [comment]
Awesome work @rutujadhanawade ! But you haven't created a separate branch while creating the PR. So make the necessary changes and let me know! :)

**Comment by rutujadhanawade** [comment]
Do you mean changing the source branch? Currently which is rutujadhanawade:master.
 Then I need to create a different PR because , isn't it?  Actually I am new to open source.

**Comment by Neilblaze** [comment]
> Do you mean changing the source branch? Currently which is rutujadhanawade:master.
> Then I need to create a different PR because , isn't it? Actually I am new to open source.

Yes, you're correct! If you're using git-cli then you can just checkout a branch from there & shift all the files/folder there.
If not, then yeah you can close this & create another pr following proper [contribution guidelines](https://github.com/ankitdobhal/Awesome-Python-Scripts/blob/master/Contribution.md).

Feel free to dm me on slack if you get stuck at any point :)

**Comment by rutujadhanawade** [comment]
Thank you @Neilblaze . I guess I will go with the second option.

**Pull request closed without merging**
