### PR TITLE
Added Instagram scraper

### PR DESCRIPTION
**Pull request by harshareddy794**
Script added for scraping Instagram data
Screenshot (62)

### CODE REVIEW

**Review by Neilblaze — APPROVED** [review]
Nice job @harshareddy794 !
LGTM! :+1:

**Comment by harshareddy794** [comment]
@Neilblaze @ankitdobhal  My PR has not yet merged can you check

**Comment by Neilblaze** [comment]
There are lots of other PR's and issues to be resolved by the mentors and PA's. No worries, @ankitdobhal will merge this when he'll be available.

**Comment by harshareddy794** [comment]
@Neilblaze  @ankitdobhal I got approval for my pr and yet to merge but some one made the same PR #255  and merged but my PR is not merged. Can you check?

**Pull request merged**
