### PR TITLE
Reddit scrapper

### PR DESCRIPTION
**Pull request by kaustubhgupta**
@SKAUL05 Please review and merge it :-)  @ankitdobhal 
This script will fetch the details of the Subreddit using Reddit API. You can define the number of posts you want to grab from each subreddit, the type of post you want: New, Rising, Hot, Top, or Controversial, and the subreddits from which want details. The following details will be scrapped from each post: 'ID', 'Author', 'Title', 'Score', 'Subreddit_Name', 'Url', 'Number_of_Comments', 'Upvote_Ratio', 'Post_Body', 'Date'.

### CODE REVIEW

**Comment by kaustubhgupta** [comment]
Issue #196

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
Remove .PNG Files
Everything else LGTM :)

**Comment by kaustubhgupta** [comment]
@SKAUL05 but that PNGs are used in the README file and displaying an example about how to use it. Should I remove that part also?

**Comment by SKAUL05** [comment]
So do one thing make a folder named output and add png files and csv file into it.
It will make directory tidy

**Comment by kaustubhgupta** [comment]
@SKAUL05 done the required changes

**Review by SKAUL05 — APPROVED** [review]
Nice job @kaustubhgupta 
Good to go @ankitdobhal 
Review & Merge

**Comment by kaustubhgupta** [comment]
@ankitdobhal can you merge this as this is reviewed and approved

**Pull request merged**
